# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 549)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.Bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_1.setGeometry(QtCore.QRect(-10, -190, 1121, 761))
        self.Bg_1.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 255);")
        self.Bg_1.setText("")
        self.Bg_1.setPixmap(QtGui.QPixmap("JARVIS/B.G-20210629T070120Z-001/B.G/Black_Template.jpg"))
        self.Bg_1.setScaledContents(True)
        self.Bg_1.setObjectName("Bg_1")
        
        self.Bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_2.setGeometry(QtCore.QRect(10, 10, 331, 251))
        self.Bg_2.setStyleSheet("background-color: rgb(81, 244, 244);")
        self.Bg_2.setText("")
        self.Bg_2.setObjectName("Bg_2")
        
        self.Bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_3.setGeometry(QtCore.QRect(350, 10, 351, 251))
        self.Bg_3.setStyleSheet("background-color: rgb(81, 244, 244);")
        self.Bg_3.setText("")
        self.Bg_3.setObjectName("Bg_3")
        
        self.Gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_3.setGeometry(QtCore.QRect(0, 270, 421, 261))
        self.Gif_3.setText("")
        self.Gif_3.setPixmap(QtGui.QPixmap("JARVIS GUI/Gif 3.gif"))
        self.Gif_3.setScaledContents(True)
        self.Gif_3.setObjectName("Gif_3")
        
        self.Gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_1.setGeometry(QtCore.QRect(14, 19, 321, 231))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("B.G-20210629T070120Z-001/B.G/Iron_Template_1.gif"))
        self.Gif_1.setScaledContents(True)
        self.Gif_1.setObjectName("Gif_1")
        
        self.Gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_2.setGeometry(QtCore.QRect(360, 20, 331, 231))
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("JARVIS GUI/Gif_6.gif"))
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("Gif_2")
        
        self.Bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_4.setGeometry(QtCore.QRect(710, 10, 211, 151))
        self.Bg_4.setStyleSheet("background-color: rgb(81, 244, 244);")
        self.Bg_4.setText("")
        self.Bg_4.setObjectName("Bg_4")
        
        self.Gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_4.setGeometry(QtCore.QRect(720, 20, 191, 131))
        self.Gif_4.setText("")
        self.Gif_4.setPixmap(QtGui.QPixmap("ExtraGui-20210629T070440Z-001/ExtraGui/Earth.gif"))
        self.Gif_4.setScaledContents(True)
        self.Gif_4.setObjectName("Gif_4")
        
        self.Text_Time = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Time.setGeometry(QtCore.QRect(680, 460, 231, 61))
        self.Text_Time.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 255, 255);\n"
"border-radius: none;")
        self.Text_Time.setObjectName("Text_Time")
        
        self.Bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_5.setGeometry(QtCore.QRect(680, 450, 231, 61))
        self.Bg_5.setText("")
        self.Bg_5.setPixmap(QtGui.QPixmap("JARVIS/B.G-20210629T070120Z-001/B.G/gggf.jpg"))
        self.Bg_5.setScaledContents(True)
        self.Bg_5.setObjectName("Bg_5")
        
        self.Bg_6 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_6.setGeometry(QtCore.QRect(680, 380, 231, 61))
        self.Bg_6.setText("")
        self.Bg_6.setPixmap(QtGui.QPixmap("JARVIS/B.G-20210629T070120Z-001/B.G/gggf.jpg"))
        self.Bg_6.setScaledContents(True)
        self.Bg_6.setObjectName("Bg_6")
        
        self.Bg_7 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_7.setGeometry(QtCore.QRect(430, 450, 231, 61))
        self.Bg_7.setText("")
        self.Bg_7.setPixmap(QtGui.QPixmap("JARVIS/B.G-20210629T070120Z-001/B.G/gggf.jpg"))
        self.Bg_7.setScaledContents(True)
        self.Bg_7.setObjectName("Bg_7")
        
        self.Text_Date = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Date.setGeometry(QtCore.QRect(680, 380, 231, 61))
        self.Text_Date.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 255, 255);\n"
"border-radius: none;")
        self.Text_Date.setObjectName("Text_Date")
        
        self.Text_Day = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Day.setGeometry(QtCore.QRect(430, 460, 231, 61))
        self.Text_Day.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 255, 255);\n"
"border-radius: none;")
        self.Text_Day.setObjectName("Text_Day")
        
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(720, 180, 191, 31))
        self.Start.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 255);\n"
"border-radius: none;")
        self.Start.setObjectName("Start")
        
        self.Bg_8 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_8.setGeometry(QtCore.QRect(710, 170, 211, 91))
        self.Bg_8.setStyleSheet("background-color: rgb(81, 244, 244);")
        self.Bg_8.setText("")
        self.Bg_8.setObjectName("Bg_8")
        
        self.Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Stop.setGeometry(QtCore.QRect(720, 220, 191, 31))
        self.Stop.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 255);\n"
"border-radius: none;")
        self.Stop.setObjectName("Stop")
        
        self.Temp = QtWidgets.QLabel(self.centralwidget)
        self.Temp.setGeometry(QtCore.QRect(430, 380, 231, 61))
        self.Temp.setText("")
        self.Temp.setPixmap(QtGui.QPixmap("B.G-20210629T070120Z-001/B.G/gggf.jpg"))
        self.Temp.setScaledContents(True)
        self.Temp.setObjectName("Temp")
        
        self.Text_Temp = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Temp.setGeometry(QtCore.QRect(430, 380, 231, 61))
        self.Text_Temp.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 255, 255);\n"
"border-radius: none;")
        self.Text_Temp.setObjectName("Text_Temp")
        
        self.YouTube = QtWidgets.QPushButton(self.centralwidget)
        self.YouTube.setGeometry(QtCore.QRect(350, 270, 111, 41))
        self.YouTube.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 255);")
        self.YouTube.setObjectName("YouTube")
        
        self.Chrome = QtWidgets.QPushButton(self.centralwidget)
        self.Chrome.setGeometry(QtCore.QRect(470, 270, 111, 41))
        self.Chrome.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 255);")
        self.Chrome.setObjectName("Chrome")
        
        self.WhatsApp = QtWidgets.QPushButton(self.centralwidget)
        self.WhatsApp.setGeometry(QtCore.QRect(590, 270, 111, 41))
        self.WhatsApp.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 255);")
        self.WhatsApp.setObjectName("WhatsApp")
        
        self.Day = QtWidgets.QLabel(self.centralwidget)
        self.Day.setGeometry(QtCore.QRect(430, 460, 231, 61))
        self.Day.setText("")
        self.Day.setPixmap(QtGui.QPixmap("B.G-20210629T070120Z-001/B.G/gggf.jpg"))
        self.Day.setScaledContents(True)
        self.Day.setObjectName("Day")
        
        self.Date = QtWidgets.QLabel(self.centralwidget)
        self.Date.setGeometry(QtCore.QRect(680, 380, 231, 61))
        self.Date.setText("")
        self.Date.setPixmap(QtGui.QPixmap("B.G-20210629T070120Z-001/B.G/gggf.jpg"))
        self.Date.setScaledContents(True)
        self.Date.setObjectName("Date")
        
        self.Time = QtWidgets.QLabel(self.centralwidget)
        self.Time.setGeometry(QtCore.QRect(680, 460, 231, 61))
        self.Time.setText("")
        self.Time.setPixmap(QtGui.QPixmap("B.G-20210629T070120Z-001/B.G/gggf.jpg"))
        self.Time.setScaledContents(True)
        self.Time.setObjectName("Time")
        
        self.Bg_1.raise_()
        self.Gif_3.raise_()
        self.Bg_2.raise_()
        self.Bg_3.raise_()
        self.Gif_1.raise_()
        self.Gif_2.raise_()
        self.Bg_4.raise_()
        self.Gif_4.raise_()
        self.Bg_5.raise_()
        self.Text_Time.raise_()
        self.Bg_6.raise_()
        self.Bg_7.raise_()
        self.Text_Date.raise_()
        self.Text_Day.raise_()
        self.Bg_8.raise_()
        self.Start.raise_()
        self.Stop.raise_()
        self.Text_Temp.raise_()
        self.YouTube.raise_()
        self.Chrome.raise_()
        self.WhatsApp.raise_()
        self.Temp.raise_()
        self.Day.raise_()
        self.Date.raise_()
        self.Time.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Start.setText(_translate("MainWindow", "START"))
        self.Stop.setText(_translate("MainWindow", "STOP"))
        self.YouTube.setText(_translate("MainWindow", "YouTube"))
        self.Chrome.setText(_translate("MainWindow", "Chrome"))
        self.WhatsApp.setText(_translate("MainWindow", "WhatsApp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
